version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: liebrejue-nextjs
    container_name: radio-liebre-jue
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3002:3000  
